package pe.uni.proyectorenta2019.view;

/**
 *
 * @author GUSTAVO
 */
public class IngresosView extends javax.swing.JFrame {

    /**
     * Creates new form ReporteView
     */
    public IngresosView() {
        initComponents();
        }
    
    private void centrar(){
        setLocationRelativeTo(null);
    }
    
    public IngresosView(double rentaNeta04, double totalRenta4, double totalQuinta, double totalRentaR4R5, double totalRentNetaR4R5  ){
            initComponents();
            centrar();
            txtRentaNeta01.setText(""+rentaNeta04);
            txtTotalRenta4.setText(""+totalRenta4);
            txtQuinta.setText(""+totalQuinta);
            txtTotalRentaR4R5.setText(""+totalRentaR4R5);
            txtTotalRentaNetaR4R5.setText(""+totalRentNetaR4R5);
            
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRentaNeta01 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalRenta4 = new javax.swing.JTextField();
        txtQuinta = new javax.swing.JTextField();
        txtTotalRentaR4R5 = new javax.swing.JTextField();
        txtTotalRentaNetaR4R5 = new javax.swing.JTextField();

        setTitle("INGRESOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(255, 102, 51))); // NOI18N

        jLabel1.setText("Renta neta obtenida por el ejercicio individual:");

        txtRentaNeta01.setEnabled(false);
        txtRentaNeta01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRentaNeta01ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total renta de cuarta categoría:");

        jLabel3.setText("Total Renta de 5ta categoría:");

        jLabel4.setText("Total Renta de 4ta y 5ta categoría:");

        jLabel5.setText("Total renta neta de 4ta y 5ta categoría:");

        txtTotalRenta4.setEnabled(false);
        txtTotalRenta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalRenta4ActionPerformed(evt);
            }
        });

        txtQuinta.setEnabled(false);
        txtQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuintaActionPerformed(evt);
            }
        });

        txtTotalRentaR4R5.setEnabled(false);
        txtTotalRentaR4R5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalRentaR4R5ActionPerformed(evt);
            }
        });

        txtTotalRentaNetaR4R5.setEnabled(false);
        txtTotalRentaNetaR4R5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalRentaNetaR4R5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRentaNeta01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(txtTotalRenta4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQuinta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalRentaR4R5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalRentaNetaR4R5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRentaNeta01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalRenta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalRentaR4R5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalRentaNetaR4R5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRentaNeta01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRentaNeta01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentaNeta01ActionPerformed

    private void txtTotalRenta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalRenta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalRenta4ActionPerformed

    private void txtQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuintaActionPerformed

    private void txtTotalRentaR4R5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalRentaR4R5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalRentaR4R5ActionPerformed

    private void txtTotalRentaNetaR4R5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalRentaNetaR4R5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalRentaNetaR4R5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtQuinta;
    private javax.swing.JTextField txtRentaNeta01;
    private javax.swing.JTextField txtTotalRenta4;
    private javax.swing.JTextField txtTotalRentaNetaR4R5;
    private javax.swing.JTextField txtTotalRentaR4R5;
    // End of variables declaration//GEN-END:variables
}
